"""Non-destructive benchmark/reproduction suite. Writes generated fixtures only."""
import asyncio
import gzip
import hashlib
import io
import json
from pathlib import Path
import random
import sys
import tarfile
import time
import uuid

BASE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE))
from storage_core import scan_local
from deep_archive import create_bundle, restore_bundle
from cdc.chunker import rabin_chunks
from storage_archive import ArchiveManager
from storage_restore import RestoreManager, RestoreRequest, RestoreType


def digest(data):
    return hashlib.sha256(data).hexdigest()


def benchmark(root):
    rng = random.Random(42)
    cases = {}
    docs = {}
    for i in range(120):
        value = {'department': 'operations', 'record': i, 'notes': 'Retain business facts and references. ' * 30,
                 'events': [{'time': j, 'status': 'completed', 'code': rng.randrange(1000, 9999)} for j in range(30)]}
        docs[f'report-{i:03}.json'] = json.dumps(value, indent=2).encode()
    for i in range(20):
        docs[f'copy-{i:03}.json'] = docs[f'report-{i:03}.json']
    cases['similar_json'] = docs
    cases['unique_small'] = {f'{i}.txt': rng.randbytes(100).hex().encode() for i in range(100)}
    cases['random_binary'] = {f'{i}.bin': rng.randbytes(512 * 1024) for i in range(4)}
    cases['already_gzip'] = {f'{i}.gz': gzip.compress(rng.randbytes(512 * 1024), mtime=0) for i in range(3)}
    base = rng.randbytes(1024 * 1024)
    cases['versioned_binary'] = {'v0.bin': base, 'v1.bin': base[:200000] + b'inserted metadata' + base[200000:],
                                 'v2.bin': base[:700000] + b'changed metadata' + base[700016:]}
    try:
        from PIL import Image
        photos = {}
        for i in range(3):
            out = io.BytesIO()
            Image.frombytes('RGB', (640, 480), rng.randbytes(640 * 480 * 3)).save(out, format='JPEG', quality=88)
            photos[f'{i}.jpg'] = out.getvalue()
        cases['jpeg_noise'] = photos
    except ImportError:
        pass
    results = []
    for name, data in cases.items():
        folder = root / name
        folder.mkdir()
        for key, content in data.items():
            (folder / key).write_bytes(content)
        start = time.perf_counter()
        report = scan_local(folder)
        scan_s = time.perf_counter() - start
        unique = {digest(content): content for content in data.values()}
        baseline = sum(min(len(content), len(gzip.compress(content, mtime=0))) for content in unique.values())
        row = {'case': name, 'files': len(data), 'original_bytes': sum(map(len, data.values())),
               'dedup_gzip_baseline_without_metadata': baseline, 'scan_seconds': round(scan_s, 4)}
        start = time.perf_counter()
        try:
            bundle = create_bundle(report, [x['id'] for x in report['files']], root / 'bundles')
            row.update(archive_seconds=round(time.perf_counter()-start, 4), codec=bundle['codec'],
                       archive_bytes=bundle['archive_bytes'], receipt_bytes=bundle['receipt_bytes'],
                       footprint=bundle['archive_bytes']+bundle['receipt_bytes'], trials=bundle['trials'])
            # Make original inputs inaccessible, retaining every generated byte in this run directory.
            offline = root / (name + '-offline')
            assert folder.parent == root and offline.parent == root
            folder.rename(offline)
            start = time.perf_counter()
            restored = restore_bundle(bundle, root / 'bundles', root / 'restored')
            row['restore_seconds'] = round(time.perf_counter()-start, 4)
            row['roundtrip_without_source'] = all((Path(restored['folder']) / key).read_bytes() == content for key, content in data.items())
            row['reduction_pct'] = round(100*(1-row['footprint']/row['original_bytes']), 2)
            row['vs_baseline_pct'] = round(100*(1-row['footprint']/baseline), 2)
        except Exception as exc:
            row.update(error=str(exc), archive_seconds=round(time.perf_counter()-start,4))
        results.append(row)
        print(json.dumps(row, ensure_ascii=False), flush=True)
    return results


async def regressions(root):
    result = {}
    result['cdc_lost_sizes'] = [n for n in range(1, 65) if b''.join(c.data for c in rabin_chunks(b'x'*n)) != b'x'*n]
    data = random.Random(77).randbytes(2 * 1024 * 1024)
    start = time.perf_counter()
    chunks = list(rabin_chunks(data))
    elapsed = time.perf_counter()-start
    result['cdc_random_probe'] = {'bytes':len(data), 'seconds':elapsed, 'MB_per_second':len(data)/1e6/elapsed,
                                  'roundtrip':b''.join(c.data for c in chunks)==data}
    versions = [data, data[:200000]+b'insert header'+data[200000:]]
    chunks = [c for version in versions for c in rabin_chunks(version)]
    unique = {c.fingerprint:c.size for c in chunks}
    result['cdc_versions'] = {'input_bytes':sum(map(len,versions)), 'unique_chunk_bytes':sum(unique.values()),
                              'ratio_without_metadata':sum(map(len,versions))/sum(unique.values())}
    source = root / 'archive-probe'
    for name in ('a','b'):
        (source / name).mkdir(parents=True)
        (source / name / 'same.txt').write_bytes((name.encode()+b' record\n')*1000)
    store = root / 'new-store'
    manager = ArchiveManager(str(store))
    manifest = await manager.create_archive([str(source)], 'evaluation')
    with tarfile.open(store/'archives'/f'{manifest.archive_id}.tar.gz') as tar:
        result['new_archive_members'] = tar.getnames()
    result['new_archive_paths'] = [e.archive_path for e in manifest.entries]
    result['reported_compressed_bytes'] = manifest.compressed_bytes
    live = await manager.restore_archive(manifest.archive_id, str(root/'live-restore'))
    result['same_name_restore'] = {'status':live.status.value, 'reported_files':live.files_restored,
                                   'actual_files':len(list((root/'live-restore').rglob('*.txt')))}
    advanced = RestoreManager(str(store))
    changed = source/'a'/'same.txt'
    changed.write_bytes(b'changed after archive')
    dest = root/'advanced-live'
    dest.mkdir()
    (dest/'same.txt').write_bytes(b'existing file must remain')
    advanced_result = await advanced.restore(RestoreRequest('verify-test',manifest.archive_id,RestoreType.FULL,str(dest),verify=True,overwrite=False))
    result['advanced_verify_overwrite'] = {'status':advanced_result.status.value,
        'verification_failures':advanced_result.verification_failures,
        'existing_preserved':(dest/'same.txt').read_bytes()==b'existing file must remain'}
    offline = root/'archive-probe-offline'
    assert source.parent == root and offline.parent == root
    source.rename(offline)
    result['verify_without_sources'] = await manager.verify_archive(manifest.archive_id)
    restored = await manager.restore_archive(manifest.archive_id,str(root/'missing-restore'))
    result['new_restore_without_sources'] = {'status':restored.status.value,'files':restored.files_restored}
    advanced_result = await advanced.restore(RestoreRequest('missing-test',manifest.archive_id,RestoreType.FULL,str(root/'advanced-missing')))
    result['advanced_restore_without_sources'] = {'status':advanced_result.status.value,'files':advanced_result.files_restored,
                                                 'skipped':advanced_result.files_skipped}
    return result


if __name__ == '__main__':
    root = BASE/'output'/'evaluation'/uuid.uuid4().hex
    root.mkdir(parents=True)
    result = {'scope':'generated fixtures, local single process; no real customer/cloud/cluster benchmark',
              'benchmarks':benchmark(root), 'regressions':asyncio.run(regressions(root))}
    (root/'results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
    print(json.dumps(result['regressions'],ensure_ascii=False,indent=2))
    print('RESULT_FILE='+str(root/'results.json'))
