const $ = id => document.getElementById(id);
const extractNav=document.createElement('button');extractNav.dataset.view='extraction';extractNav.textContent='▧　图片信息提取';document.querySelector('nav').insertBefore(extractNav,document.querySelector('[data-view="audit"]'));
let bundleReceipt = null;
let report = null, manifest = null, source = 'local', busy = false;
const fmt = n => {if(!n)return '0 B'; const units=['B','KB','MB','GB','TB','PB'];const i=Math.min(5,Math.floor(Math.log(n)/Math.log(1000)));return `${(n/1000**i).toLocaleString('zh-CN',{maximumFractionDigits:2})} ${units[i]}`;};
const esc = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => '¥'+Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
async function api(path,body){const res=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Storage-App':'1'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'请求失败');return data;}
function notice(text,error=false){$('notice').hidden=false;$('notice').textContent=text;$('notice').className=error?'error':'';}
function view(name){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===name));$('page-name').textContent={overview:'存储总览',inventory:'资料清单',optimize:'优化与验证',extraction:'图片信息提取',audit:'操作记录'}[name];if(name==='audit')loadAudit().catch(e=>notice(e.message,true));}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(b=>{if(!b.dataset.view)b.disabled=value;});}
async function job(path,body,onDone){if(busy)return;setBusy(true);try{const {job_id}=await api(path,body);for(;;){const state=await api('/api/job/'+job_id);if(state.status==='error')throw Error(state.error);if(state.status==='done'){await onDone(state.result);break;}notice(`正在${state.action} · 已处理 ${state.progress.files||0} 个文件${state.progress.current?' · '+state.progress.current:''}`);await new Promise(resolve=>setTimeout(resolve,700));}}catch(e){notice(e.message,true);}finally{setBusy(false);}}
function showReport(value){report=value;manifest=null;bundleReceipt=null;document.getElementById('bundle-result').textContent='';document.getElementById('extraction-result').textContent='';$('total').textContent=fmt(report.summary.bytes);$('file-count').textContent=`${report.demo?'示例资料 · ':''}${report.summary.files.toLocaleString()} 个文件 / 对象`;$('duplicate').textContent=report.source==='s3'?'未验证':fmt(report.summary.duplicate_bytes);$('text-size').textContent=fmt(report.summary.text_bytes);$('coverage').textContent=report.complete?(report.errors.length?'完成 · 有跳过项':'扫描完成'):'部分盘点';$('source-label').textContent=report.root;$('archive-result').textContent='';$('cost-result').textContent='';$('restore').hidden=true;const kinds=Object.entries(report.summary.categories).sort((a,b)=>b[1]-a[1]);$('composition').className='';$('composition').innerHTML=kinds.map(([name,bytes])=>`<div class="bar-row"><div class="bar-label"><span>${esc(name)}</span><b>${fmt(bytes)}</b></div><div class="bar"><div></div></div></div>`).join('')||'<p class="muted">目录内没有可读取的文件</p>';document.querySelectorAll('.bar>div').forEach((e,i)=>e.style.width=`${report.summary.bytes?kinds[i][1]/report.summary.bytes*100:0}%`);$('scan-errors').innerHTML=report.errors.slice(0,30).map(e=>`<div class="error-line">${esc(e.path)}：${esc(e.error)}</div>`).join('');renderFiles();notice(`${report.demo?'示例资料':'资料库'}盘点完成：${report.summary.files} 个文件 / 对象，${report.errors.length} 项异常。${report.scope_note||'原始文件未修改。'}`);}
function renderFiles(){if(!report)return;const query=$('search').value.toLowerCase(),filter=$('filter').value;const items=report.files.filter(f=>(f.path.toLowerCase().includes(query))&&(filter==='all'||filter==='duplicates'&&f.duplicate_of||filter==='eligible'&&f.archive_eligible));$('files').innerHTML=items.slice(0,500).map(f=>`<tr><td>${esc(f.name)}<small>${esc(f.path)}</small></td><td>${esc(f.category)}</td><td>${fmt(f.size)}</td><td><span class="badge ${!f.duplicate_of&&!f.archive_eligible?'gray':''}">${f.duplicate_of?'已验证重复':f.archive_eligible?'可测试无损归档':report.source==='s3'?'仅元数据盘点':'保留 / 待评估'}</span></td></tr>`).join('');$('table-info').textContent=`匹配 ${items.length} 项，显示前 ${Math.min(items.length,500)} 项。完整清单可导出 CSV。`;}
$('search').oninput=renderFiles;$('filter').onchange=renderFiles;
function setSource(value){source=value;$('local-fields').hidden=value!=='local';$('s3-fields').hidden=value!=='s3';$('root').required=value==='local';$('bucket').required=value==='s3';$('local-tab').classList.toggle('selected',value==='local');$('s3-tab').classList.toggle('selected',value==='s3');}
$('local-tab').onclick=()=>setSource('local');$('s3-tab').onclick=()=>setSource('s3');
$('scan-form').onsubmit=e=>{e.preventDefault();job('/api/scan',{source,root:$('root').value,bucket:$('bucket').value,prefix:$('prefix').value,region:$('region').value,profile:$('profile').value,endpoint:$('endpoint').value},async result=>{showReport(result);await refresh();});};
$('demo').onclick=()=>job('/api/demo',{},async result=>{showReport(result);view('overview');await refresh();});
async function refresh(){const status=await api('/api/status');$('history').innerHTML=status.reports.slice(0,10).map(r=>`<div class="history-item"><div><b>${esc(r.root)}</b><small>${r.source==='s3'?'S3 对象存储':'本地目录'} · ${fmt(r.summary.bytes)} · ${new Date(r.created_at).toLocaleString('zh-CN')}</small></div><button class="text-button" data-report="${r.id}">查看报告 →</button></div>`).join('')||'暂无盘点记录';document.querySelectorAll('[data-report]').forEach(b=>b.onclick=async()=>{try{showReport(await api('/api/report/'+b.dataset.report));}catch(e){notice(e.message,true);}});if(!status.s3_available)$('s3-tab').title='需安装 requirements.txt 中的 boto3';}
$('refresh').onclick=()=>refresh().catch(e=>notice(e.message,true));
$('export').onclick=()=>{if(!report)return notice('请先扫描或选择一个报告',true);window.location.href='/api/export/'+report.id;};
$('archive').onclick=()=>{if(!report)return notice('请先扫描一个本地目录',true);if(report.source!=='local')return notice('当前云端功能为只读盘点；不下载或修改云端对象。',true);const ids=report.files.filter(f=>f.archive_eligible&&!f.duplicate_of).slice(0,500).map(f=>f.id);if(!ids.length)return notice('没有符合条件的非重复文本文件',true);job('/api/archive',{report_id:report.id,ids},result=>{manifest=result;const original=result.items.reduce((s,x)=>s+x.original_bytes,0),packed=result.items.reduce((s,x)=>s+x.archive_bytes,0);$('archive-result').innerHTML=`<div class="result-line"><span>已验证归档</span><strong>${result.items.length} 个文件</strong></div><div class="result-line"><span>原始容量 → 归档容量</span><strong>${fmt(original)} → ${fmt(packed)}</strong></div><div class="result-line"><span>归档替换后的潜在净缩减</span><strong>${fmt(result.net_potential_bytes)}</strong></div><p class="hint">已扣除归档清单。原件仍在；归档、报告和恢复副本当前会增加占用。记录 ID：${esc(result.id)}</p>${result.errors.map(e=>`<div class="error-line">${esc(e.path)}：${esc(e.error)}</div>`).join('')}`;$('restore').hidden=!result.items.length;notice(`归档完成，${result.items.length} 项通过完整内容校验，${result.errors.length} 项跳过。`);});};
$('restore').onclick=()=>{if(manifest)job('/api/restore',{manifest_id:manifest.id},result=>notice(`已恢复 ${result.files.length} 个文件并校验一致，保存于：${result.folder}`));};
$('cost-form').onsubmit=async e=>{e.preventDefault();if(!report)return notice('请先扫描或选择一个报告',true);try{const result=await api('/api/economics',{report_id:report.id,manifest_id:manifest?.id,bundle_id:bundleReceipt?.id,local_rate:$('local-rate').value,cloud_rate:$('cloud-rate').value,processing_cost:$('processing-cost').value});$('cost-result').innerHTML=`<div class="result-line"><span>当前方案潜在净缩减</span><strong>${fmt(result.potential_bytes)}</strong></div><div class="result-line"><span>本地情景 · 年度毛收益</span><strong>${money(result.local_annual)}</strong></div><div class="result-line"><span>本地情景 · 首年净收益</span><strong>${money(result.local_first_year_net)}</strong></div><div class="result-line"><span>云端情景 · 年度毛收益</span><strong>${money(result.cloud_annual)}</strong></div><div class="result-line"><span>云端情景 · 首年净收益</span><strong>${money(result.cloud_first_year_net)}</strong></div><p class="hint">${esc(result.note)}</p>${report.source==='s3'?'<p class="hint">当前 S3 盘点未验证重复或压缩收益，因此潜在缩减暂计 0；不表示不存在优化机会。</p>':''}`;}catch(err){notice(err.message,true);}};
async function loadAudit(){const items=await api('/api/audit');$('audit-list').innerHTML=items.map(x=>`<div class="audit-item"><b>${esc(x.action)}</b><small>${new Date(x.at).toLocaleString('zh-CN')} · ${esc(JSON.stringify(x.details))}</small></div>`).join('')||'<p class="muted">暂无操作记录</p>';}
refresh().catch(e=>notice(e.message,true));
$('extract').onclick=()=>{if(!report||report.source!=='local')return notice('请先选择包含图片的本地盘点报告',true);const ids=report.files.filter(f=>/\.(png|jpe?g|bmp)$/i.test(f.name)&&!f.duplicate_of).slice(0,50).map(f=>f.id);if(!ids.length)return notice('当前报告没有支持提取的图片',true);job('/api/extract',{report_id:report.id,ids},result=>{$('extraction-result').innerHTML=result.items.map(f=>`<div class="audit-item"><b>${esc(f.source_path)}</b><small>${fmt(f.original_bytes)} 原图 / ${fmt(f.derived_bytes)} 文本与结构 · ${esc(f.language)} · 待人工审核</small><div class="ocr-compare"><img loading="lazy" src="/api/source/${result.report_id}/${f.file_id}" alt="原图对照"><pre class="ocr-text">${esc(f.text)}</pre></div><small>文本保存于 ${esc(f.text_path)}</small></div>`).join('')+result.errors.map(e=>`<div class="error-line">${esc(e.path)}：${esc(e.error)}</div>`).join('');notice(`完成 ${result.items.length} 张图片提取，${result.errors.length} 项跳过。文字未审核，未删除原图。`);});};

const deepPanel=document.createElement('article');
deepPanel.className='panel deep-panel';
deepPanel.innerHTML=`<div class="panel-title"><div><p class="eyebrow">DEEP COMPACTION</p><h2>整批深度归档</h2></div><span class="pill">v0.2 · 三算法实测择优</span></div><p class="muted">跨文件去重 + 整批压缩，适合大量小文件、相似文档与重复资料。支持所有普通文件类型，逐一验证内容；实测 GZIP / BZIP2 / XZ 后仅保留最小方案。</p><p class="hint">当前报告前 2000 个非硬链接文件，单批最多 20GB。比逐文件压缩更耗时；原件保留，未自动释放空间。同批内容再次归档会复用结果，不继续堆积副本。</p><button id="deep-archive" class="primary">生成更小的整批归档 →</button><div id="bundle-result" class="result"></div>`;
document.getElementById('optimize').prepend(deepPanel);
$('deep-archive').onclick=()=>{
 if(!report||report.source!=='local')return notice('请先扫描本地或已挂载 NAS 的目录',true);
 const ids=report.files.filter(f=>!f.hardlink_of&&(f.link_count??1)===1).slice(0,2000).map(f=>f.id);
 job('/api/bundle',{report_id:report.id,ids},result=>{
  bundleReceipt=result;
  $('cost-result').textContent='已切换到深度归档方案，请重新计算成本。';
  const gzip=result.trials.find(t=>t.codec==='gzip');
  $('bundle-result').innerHTML=`<div class="metrics"><article><span>原始内容</span><strong>${fmt(result.original_bytes)}</strong><small>${result.file_count} 个文件</small></article><article><span>实际归档大小</span><strong>${fmt(result.archive_bytes)}</strong><small>${esc(result.codec.toUpperCase())} · 包含内部恢复清单</small></article><article><span>潜在净缩减</span><strong>${fmt(result.net_potential_bytes)}</strong><small>已扣除归档及回执，原件仍保留</small></article><article class="mint"><span>相比同批 GZIP 额外缩减</span><strong>${fmt(gzip.bytes-result.archive_bytes)}</strong><small>${result.unique_contents} 份唯一内容</small></article></div><table><thead><tr><th>算法</th><th>实测体积</th><th>压缩及验证时间</th><th>结果</th></tr></thead><tbody>${result.trials.map(t=>`<tr><td>${esc(t.codec.toUpperCase())}</td><td>${fmt(t.bytes)}</td><td>${t.seconds} 秒</td><td>${t.codec===result.codec?'已保留':'已丢弃较大候选'}</td></tr>`).join('')}</tbody></table><p class="hint">${result.reused?'复用了已验证归档。':''}按文件内容精确恢复目录及重复副本；不保存 ACL、扩展属性或备用数据流。输出可下载后用于云端冷归档，尚未自动上传或删除云端原件。净缩减不包含工作台报告与日志占用。</p><div class="bundle-actions"><a class="secondary" href="/api/bundle-download/${result.id}">下载完整归档 ↓</a><button id="restore-bundle" class="secondary">恢复目录并验证</button></div>`;
  $('restore-bundle').onclick=()=>job('/api/restore-bundle',{bundle_id:result.id},restored=>notice(`已恢复 ${restored.file_count} 个文件，内容校验一致：${restored.folder}`));
  notice(`${result.reused?'复用':'完成'}深度归档：${fmt(result.original_bytes)} → ${fmt(result.archive_bytes)}。原件未删除，实际释放仍为 0。`);
 });
};

const vaultNav=document.createElement('button');
vaultNav.dataset.view='vault';vaultNav.textContent='▣　企业无损保管';document.querySelector('nav').append(vaultNav);
const vaultPanel=document.createElement('section');vaultPanel.id='vault';vaultPanel.className='view';vaultPanel.hidden=true;
vaultPanel.innerHTML=`<article class="panel"><div class="panel-title"><h2>企业无损保管</h2><span class="pill">本机处理 · 不上传内容</span></div><p class="muted">折叠存入 → 独立还原 → 确认收妥 → 清理保管归档。恢复时逐文件校验内容，原始目录始终由企业自行管理。</p><p class="hint">保证文件字节和相对路径一致；新任务保留修改时间；暂不保留 ACL、创建时间、空目录及备用数据流。当前未加密，不提供远程托管。系统快照、外部备份和已有旧版任务不在本次清理范围内。</p><form id="vault-fold"><label for="vault-source">企业资料目录</label><input id="vault-source" required placeholder="输入独立的待折叠目录"><button class="primary">无损折叠并验证</button></form><label for="vault-destination">取出到企业指定目录</label><input id="vault-destination" placeholder="输入已经存在的交付目录"><p class="hint">将在此目录内新建独立子目录，不覆盖已有文件。存入后原件仍保留，因此暂不计实际释放空间。</p><button id="vault-refresh" class="secondary">刷新保管清单</button><div id="vault-records"></div></article>`;
document.querySelector('main').insertBefore(vaultPanel,document.querySelector('footer'));
vaultNav.onclick=()=>{view('vault');$('page-name').textContent='企业无损保管';loadVault().catch(e=>notice(e.message,true));};
async function loadVault(){
 const records=await api('/api/vault');
 $('vault-records').innerHTML=records.map(r=>`<div class="audit-item"><b>${esc(r.id)}</b><p>${esc({folded:'已折叠',awaiting_receipt:'已还原，等待收妥确认',releasing:'清理待完成，可重试',released:'已取走，保管归档已清理'}[r.status]||r.status)} · ${r.file_count} 个文件</p>${r.receipt?`<p>原始 ${fmt(r.original_bytes)} → 归档 ${fmt(r.receipt.archive_bytes)}；原件仍保留</p>`:''}${r.health?`<p>最近巡检：${r.health.status==='healthy'?'通过':'失败，请检查'} · ${esc(r.health.at)}</p>`:''}${['folded','awaiting_receipt'].includes(r.status)?`<button class="secondary" data-health="${r.id}">全量完整性巡检</button>`:''}${r.status==='folded'?`<button class="secondary" data-catalog="${r.id}">查看目录并选择文件</button><div id="catalog-${r.id}"></div>`:''}${r.delivery?`<p>交付目录：${esc(r.delivery)}</p>`:''}${r.status==='folded'?`<button class="secondary" data-checkout="${r.id}">还原到指定目录</button>`:''}${['awaiting_receipt','releasing'].includes(r.status)?`<label><input type="checkbox" data-ack="${r.id}"> 我已收妥交付文件，清理本任务保管归档</label><button class="secondary" data-release="${r.id}">重新核验并完成取走</button>`:''}${r.status==='released'?'<p class="hint">仅保留不含文件名及内容的交接状态记录。</p>':''}</div>`).join('')||'<p class="muted">暂无保管任务</p>';
 bindVaultInspection();
 document.querySelectorAll('[data-checkout]').forEach(b=>b.onclick=()=>{const destination=$('vault-destination').value.trim();if(!destination)return notice('请填写交付目录',true);job('/api/vault/checkout',{id:b.dataset.checkout,destination},async()=>{await loadVault();notice('独立还原并校验完成，请检查交付目录后确认收妥。');});});
 document.querySelectorAll('[data-release]').forEach(b=>b.onclick=()=>{const id=b.dataset.release;if(!document.querySelector(`[data-ack="${id}"]`).checked)return notice('请先检查交付文件并勾选收妥确认',true);job('/api/vault/release',{id,acknowledged:true},async()=>{await loadVault();notice('交付文件复核通过，本任务保管归档已清理。');});});
}
$('vault-refresh').onclick=()=>loadVault().catch(e=>notice(e.message,true));
$('vault-fold').onsubmit=e=>{e.preventDefault();job('/api/vault/fold',{root:$('vault-source').value},async()=>{await loadVault();notice('无损折叠完成，归档已独立验证，源文件未修改。');});};

function bindVaultInspection(){
 document.querySelectorAll('[data-health]').forEach(b=>b.onclick=()=>job('/api/vault/health',{id:b.dataset.health},async result=>{await loadVault();notice(result.status==='healthy'?`全量巡检通过，已校验 ${result.verified_files} 个文件。`:'巡检失败，保管内容继续保留，请检查介质和归档。',result.status!=='healthy');}));
 document.querySelectorAll('[data-catalog]').forEach(b=>b.onclick=()=>job('/api/vault/catalog',{id:b.dataset.catalog},result=>{
  const holder=$('catalog-'+result.id);
  holder.innerHTML=`<p class="hint">选取资料到企业指定目录会保留原归档，不完成整批交接。当前压缩格式仍需顺序读取归档；选择性取出主要减少落盘空间。</p><label>按路径筛选<input data-catalog-search placeholder="输入文件名或目录"></label><div data-file-options>${result.files.map((f,i)=>`<label data-file-row><input type="checkbox" data-pick="${i}"> ${esc(f.path)} · ${fmt(f.size)}</label>`).join('')}</div><button class="secondary" data-retrieve>仅取出勾选文件</button>`;
  holder.querySelector('[data-catalog-search]').oninput=e=>holder.querySelectorAll('[data-file-row]').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(e.target.value.toLowerCase()));
  holder.querySelector('[data-retrieve]').onclick=()=>{
   const paths=[...holder.querySelectorAll('[data-pick]:checked')].map(e=>result.files[Number(e.dataset.pick)].path);
   const destination=$('vault-destination').value.trim();
   if(!paths.length||!destination)return notice('请勾选文件并填写交付目录',true);
   job('/api/vault/retrieve',{id:result.id,paths,destination},out=>notice(`已取出并验证 ${out.file_count} 个文件：${out.folder}。归档继续保留。`));
  };
  notice(`目录校验完成，共 ${result.files.length} 个文件。`);
 }));
}
